controller:
  persistence:
    existingClaim: "jenkins-pvc"
  serviceType: NodePort
  nodePort: 32000
  
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
  volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
