# Все настройки для основного компонента Jenkins - контроллера
controller:
  # Настройки постоянного хранилища
  persistence:
    # Мы говорим чарту: "Не создавай новый PVC. Используй тот, что уже существует
    # и называется 'jenkins-pvc'". Это мы создали на предыдущем шаге.
    existingClaim: "jenkins-pvc"
  # Настройки Сервиса (как получить доступ к Jenkins по сети)
  serviceType: NodePort # Мы выбираем тип 'NodePort'
  # 'NodePort' открывает указанный порт на IP-адресе самого сервера (узла k3s).
  # Это самый простой способ получить доступ к веб-интерфейсу для обучения.
  nodePort: 32000 # Мы хотим, чтобы Jenkins был доступен по порту 32000.
  
  # Запросы и лимиты ресурсов. Очень важно для стабильности кластера!
  resources:
    # Запросы (requests): сколько ресурсов Jenkins'у ГАРАНТИРОВАННО будет выделено.
    requests:
      cpu: "500m"      # 'm' означает 'millicores'. 500m = половина одного ядра CPU.
      memory: "512Mi"  # 'Mi' означает 'Mebibytes'.
    # Лимиты (limits): МАКСИМУМ ресурсов, которые Jenkins может потреблять.
    # Если он попытается использовать больше, Kubernetes его ограничит или перезапустит.
    limits:
      cpu: "1"         # Не больше одного полного ядра CPU.
      memory: "1Gi"    # Не больше одного гибибайта памяти.
